# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: Docker@2
  inputs:
    containerRegistry: 'acraccess'
    repository: 'myrepo'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(a0d0b0f0-c817-4764-92df-4127321537d7)'
    KeyVaultName: 'cicdkv01'
    SecretsFilter: 'EditableOptions'


# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
